title: Aren Dang # your name (or website title) here
logo: "/images/avatar.jpg?raw=true" # your photo (or logo) here
description: > # your text below (remove <br> elements if you don't need line breaks)
  I have graduated with a degree in Computer Science, majoring in Data Science with a GPA of 3.7/4.0. 
  Over the last three years, I completed multiple projects spanning data analytics and machine learning applications, each aimed at addressing practical business challenges. 
  I am eager to leverage my analytical skills in Data Science and AI entry-level positions.

  <br><br>
  <a href="https://www.linkedin.com/in/nhat-anh-dang/">View My LinkedIn Profile</a> 
  
remote_theme: pages-themes/minimal@v0.2.0
plugins:
- jekyll-remote-theme
