title: Nhat Anh Dang # your name (or website title) here
logo: "/images/avatar.jpg?raw=true" # your photo (or logo) here
description: > # your text below (remove <br> elements if you don't need line breaks)
  Current undergraduate student in Computer Science, graduating in December 2024. Strong foundation in applied mathematics and statistics. Experienced in leveraging data manipulation, analysis, and visualisation techniques to derive actionable insights. 
  <br><br>
  <a href="https://www.linkedin.com/in/nhat-anh-dang/">View My LinkedIn Profile</a> 
  
remote_theme: pages-themes/minimal@v0.2.0
plugins:
- jekyll-remote-theme
google_analytics: G-9EJGWD3J06 # your Google Analytics tracking ID here
