title: Aren Dang # your name (or website title) here
logo: "/images/avatar.jpg?raw=true" # your photo (or logo) here
description: > # your text below (remove <br> elements if you don't need line breaks)
  I am a current undergraduate student in Computer Science, majoring in Data Science. I have completed several projects that range from data analytics to machine learning applications, tackling real-world business challenges.
  Additionally, I have hands-on experience with cloud computing platforms such as AWS and Azure.
  <br><br>
  <a href="https://www.linkedin.com/in/nhat-anh-dang/">View My LinkedIn Profile</a> 
  
remote_theme: pages-themes/minimal@v0.2.0
plugins:
- jekyll-remote-theme
