title: Nhat Anh Dang # your name (or website title) here
logo: "/images/avatar.jpg?raw=true" # your photo (or logo) here
description: > # your text below (remove <br> elements if you don't need line breaks)
  Passionate data enthusiast with a foundation in statistics and applied mathematics. Experienced in leveraging data manipulation, analysis, and visualisation techniques to derive actionable insights. 
  <br><br>
  <a href="https://www.linkedin.com/in/nhat-anh-dang/">View My LinkedIn Profile</a> 
  
